### ISSUE TITLE
Recovery timeout occurred in dispatched state cmdlet

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2215]
Shut down active smart server during cmdlet executing process in HA mode. The rule is 'file:every 5s | path matches "/compress/*" | compress'. There are two files in '/compress' path.
![image](https://user-images.githubusercontent.com/32612402/102952913-2f923580-450b-11eb-8f95-da3128661f0d.png)
Then, the standby server is activated. The two cmdlets didn't recover normally. 
![image](https://user-images.githubusercontent.com/32612402/102953520-75033280-450c-11eb-807c-f4d0211c6a11.png)
The 446 cmldet which executed on standby server timeout occurred.
![image](https://user-images.githubusercontent.com/32612402/102953528-79c7e680-450c-11eb-8122-92c39988a550.png)
The 445 cmdlet which executed on agent is  finished. But the cmdlet state is still DISPATCHED.
![image](https://user-images.githubusercontent.com/32612402/102953595-ab40b200-450c-11eb-8479-31a7b4b1dc01.png)
These failed tasks show that the two files are compressed.
![image](https://user-images.githubusercontent.com/32612402/102953643-c4e1f980-450c-11eb-827a-5b7d6dc81d9c.png)
![image](https://user-images.githubusercontent.com/32612402/102953705-e2af5e80-450c-11eb-9251-fd86d0951cdf.png)

**Comment by lipppppp** [comment]
The same issue exists in ec and other functions. We hope the cmdlet can be recovered normally when HA happens. And ensure that temperature information won't be lost.

**Comment by philo-he** [comment]
Please see PR #2217.

**Comment by philo-he** [comment]
The so-called recovery means, for unfinished action loaded from metastore, track its status like a normal action, and report an unsuccessful status generated for timeout action (long time no report). There is no issue for many actions. For such action, even though it is successfully executed actually, timeout report has no impact in rule case due to new action will be created to try again. And it is also OK for some action by just giving a timeout report to let user check the actual execution status. If getting actual status is necessary in SSM for taking over data temperature, or something else, we need to add support to speculate action status according to file state or other information.

**Comment by lipppppp** [comment]
Thanks for your support. This is a good solution. And I think it would be better if we could set timeout as a configuration item.

**Comment by philo-he** [comment]
Fixed by #2217. For timeout configuration, you can consider to make TIMEOUT_MULTIPLIER configurable on your side if needed. 

We had a largest status report interval (500ms by default) that is configurable. And considering timeout depends on report interval, we use this max report interval multiply TIMEOUT_MULTIPLIER to get timeout value. From my perspective, the current code may work for most general cases.
